<?xml version="1.0" encoding="UTF-8"?>
<Layout version="1.6.1">
  <Mode>Vertical</Mode>
  <X>851</X>
  <Y>3</Y>
  <VerticalWidth>320</VerticalWidth>
  <VerticalHeight>720</VerticalHeight>
  <HorizontalWidth>-1</HorizontalWidth>
  <HorizontalHeight>-1</HorizontalHeight>
  <Settings>
    <TextColor>FFFFFFFF</TextColor>
    <BackgroundColor>FF494243</BackgroundColor>
    <BackgroundColor2>00000000</BackgroundColor2>
    <ThinSeparatorsColor>FFFFFFFF</ThinSeparatorsColor>
    <SeparatorsColor>FFFFFFFF</SeparatorsColor>
    <PersonalBestColor>FF16A6FF</PersonalBestColor>
    <AheadGainingTimeColor>FFC537D0</AheadGainingTimeColor>
    <AheadLosingTimeColor>FF1D379A</AheadLosingTimeColor>
    <BehindGainingTimeColor>FFCC5C52</BehindGainingTimeColor>
    <BehindLosingTimeColor>FFCC1200</BehindLosingTimeColor>
    <BestSegmentColor>FFD8AF1F</BestSegmentColor>
    <UseRainbowColor>False</UseRainbowColor>
    <NotRunningColor>FF3843D8</NotRunningColor>
    <PausedColor>FF7A7A7A</PausedColor>
    <TextOutlineColor>FF000000</TextOutlineColor>
    <ShadowsColor>BE000000</ShadowsColor>
    <TimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAMEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAABAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></TimesFont>
    <TimerFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAApCZWJhcyBOZXVlOY4bQgX8////GFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQEAAAAHdmFsdWVfXwAIAgAAAAEAAAAF+////xtTeXN0ZW0uRHJhd2luZy5HcmFwaGljc1VuaXQBAAAAB3ZhbHVlX18ACAIAAAACAAAACw==]]></TimerFont>
    <TextFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAVBcmlhbAAAEEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAABAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></TextFont>
    <AlwaysOnTop>True</AlwaysOnTop>
    <ShowBestSegments>True</ShowBestSegments>
    <AntiAliasing>True</AntiAliasing>
    <DropShadows>True</DropShadows>
    <BackgroundType>Image</BackgroundType>
    <BackgroundImage><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAHgYAAAL/2P/gABBKRklGAAEBAQAAAAAAAP/bAEMACQYHEBIQFQ8PEBUVFRUVFRUVFRUVFRUVFRUVFxcXFRUVFRgdKCAYHSUdFRUhMSElKSsuLi4XHzM4My03KC0uK//bAEMBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIAUIAnAMBIgACEQEDEQH/xAAcAAEBAAIDAQEAAAAAAAAAAAAAAQMFAgQHBgj/xAAzEAEAAQIEBAQDBgcAAAAAAAAAAQIDBAUREgYhQVETMWFxB4GhMkJSYpGxFBUiIzND0f/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDxUAAABFAAQFBAUEAFQAAFEADUNAUAAAAEBQQFABFABFQAABUAAAFAEVAFEAUABFARRAFRQEAAABUAFAAAEUQBQgEUABAAAAVAFEAAAFARUUAAARQAQBRAAAAUBAAVCYBQAAAAAAAAQBRAVBQQAAAAFAAABYpBBy2m0HEctptBxHLabQcRy2m0HAc9ptBwVdq7QcBZhAAAUACGTRjhkkAFBBz8OXKizrOgMQ7tOBq7MlOXVdga7RdG0jLJ7OX8unsDUaGjbRgJ7MN7CTHQGuVzrp0cASpjZK2MAAFAAhllihkkByiFilzppB2sFpM7anYv4SbdXOOXT1h1LUaS+oy6mnE2/Aq5Vx/jq7z+GZ9Qd7Jsti9RFVPzbi1w96Nd8O8T4WL/AIa9yiqdvPpV0+r2m1klMdAeV1cP/ldTEZHMdHsNeTU9nRv5BE1RGnUHl9vh2duu1ps0ymaej3e5ktG3SIh8RxTlGkTpAPEcfY0l0Jh9PnmF0mXzV2OYMdTGyVuACACgAQyMdLLEag7WEjm3OHyyK45cpa3BYWuZ1inV9TlFqYmN0THvGgNPiMpuUedM6OtavTbmJjlMPYcmwFFynZXTExLU8X/DC5sm9g43x5zb+9Ht+IGny/bjopv2p0xNqImumPO5RHlXH5o6/r3e5ZLipu2LddXnNMbveOUvy5lt/EYTEU10bqLlur2mJjziYn6w/THCWa28VhaL1FO2Z+3RH3a+unp1gG5QAGh4lwkTRM+jfvmeMMVV4c0Ucu8g8T4s03zTS+KvRzfa5/a0mXx2K8wdStjZK2MAAFAAh2LM82CGSPMH2vDk06xq9Y4dwtmqI3UxPvDxPIqucay9a4UxFERGtX1B99h8nw8c6aIj25fs2NFERGkOjYzGzFMa3KY96oLuc4emNZuRoDp59wng8ZO69ajfH+ynSKvnP3vm7OR5NbwtHh25mYfM5z8T8Bh50mZqntS1OH+NuXzVpXZvUx+LSKoj5RzB6eOhkuc4fF2ov4a7FyiesdJ7VR5xLvgkPmuK6eU+z6Z8hxhiYjWNQeR8SecviMXPN9bxFe1mXx+Jq5g61bGyVsYAAKABDLLFDLIM+HxNVPlOjbYXN6487lXtrp+zQmoPraeLZtx/RrMtZmPFGKvcpuTTHaP+tKAtVUzzmdZ7ygA9A+Cuf1YfMacPNX9vERNEx036a0T9Jj5v0Y/IvDV6aMbh7kedN63V+lUP1Ji87opjWJB3cdiot06683l3Fma6683e4h4k110l5pnma7pnmDV5vitZlobks+Jv6y6oJWxslbGAKagAAsOcscMkgAAAAAA7mTTpfoq7Tr+j0LGcSzMfaebYevbOrPcxcz1BvsxziaurQYjEzMsFV2ZYwWqUAErcHOvyYwBUBQQFhmiNWFYqBm8M2ezFvN4Mvh+yeH6se83gy7Dw/Vi3m8GXZ6mz1hi3m8GTwzw/WGPebwZfD9U2erHvN4FbiTKAAAoAAAAAAACKAIKCCgIKgAACoAoAAAAAAAISoAgoCKAgAKgAAAqKAAgCgAIoAICiACiAAAqAAACgAgKAAAACCoCooCAoIKgKIAqACggCooAAAACCgCAAoCCoACgiiSCgAigAipAKAAigAgAKAIAAAKIAqAAACwIAogCyIAqACwgAAASAAsAD/9kL]]></BackgroundImage>
    <ImageOpacity>1</ImageOpacity>
    <ImageBlur>0</ImageBlur>
    <Opacity>1</Opacity>
    <MousePassThroughWhileRunning>False</MousePassThroughWhileRunning>
  </Settings>
  <Components>
    <Component>
      <Path>LiveSplit.Title.dll</Path>
      <Settings>
        <Version>1.7.3</Version>
        <ShowGameName>True</ShowGameName>
        <ShowCategoryName>True</ShowCategoryName>
        <ShowAttemptCount>True</ShowAttemptCount>
        <ShowFinishedRunsCount>False</ShowFinishedRunsCount>
        <OverrideTitleFont>False</OverrideTitleFont>
        <OverrideTitleColor>False</OverrideTitleColor>
        <TitleFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAUEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAgAAAAs=]]></TitleFont>
        <SingleLine>True</SingleLine>
        <TitleColor>FFFFFFFF</TitleColor>
        <BackgroundColor>00494243</BackgroundColor>
        <BackgroundColor2>FF494243</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <DisplayGameIcon>True</DisplayGameIcon>
        <ShowRegion>False</ShowRegion>
        <ShowPlatform>False</ShowPlatform>
        <ShowVariables>True</ShowVariables>
        <TextAlignment>0</TextAlignment>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Subsplits.dll</Path>
      <Settings>
        <Version>1.7</Version>
        <CurrentSplitTopColor>B8E024EE</CurrentSplitTopColor>
        <CurrentSplitBottomColor>CCCB12DF</CurrentSplitBottomColor>
        <VisualSplitCount>14</VisualSplitCount>
        <SplitPreviewCount>1</SplitPreviewCount>
        <MinimumMajorSplits>0</MinimumMajorSplits>
        <DisplayIcons>True</DisplayIcons>
        <ShowThinSeparators>False</ShowThinSeparators>
        <AlwaysShowLastSplit>True</AlwaysShowLastSplit>
        <SplitWidth>20</SplitWidth>
        <SplitTimesAccuracy>Seconds</SplitTimesAccuracy>
        <BeforeNamesColor>FFFFFFFF</BeforeNamesColor>
        <CurrentNamesColor>FFFFFFFF</CurrentNamesColor>
        <AfterNamesColor>FFFFFFFF</AfterNamesColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BeforeTimesColor>FFFFFFFF</BeforeTimesColor>
        <CurrentTimesColor>FFFFFFFF</CurrentTimesColor>
        <AfterTimesColor>FFFFFFFF</AfterTimesColor>
        <OverrideTimesColor>False</OverrideTimesColor>
        <LockLastSplit>True</LockLastSplit>
        <IconSize>24</IconSize>
        <IconShadows>True</IconShadows>
        <SplitHeight>6</SplitHeight>
        <CurrentSplitGradient>Vertical</CurrentSplitGradient>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>01FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <SeparatorLastSplit>True</SeparatorLastSplit>
        <DeltasAccuracy>Tenths</DeltasAccuracy>
        <DropDecimals>True</DropDecimals>
        <OverrideDeltasColor>False</OverrideDeltasColor>
        <DeltasColor>FFFFFFFF</DeltasColor>
        <HeaderComparison>Current Comparison</HeaderComparison>
        <HeaderTimingMethod>Current Timing Method</HeaderTimingMethod>
        <Display2Rows>False</Display2Rows>
        <IndentBlankIcons>True</IndentBlankIcons>
        <IndentSubsplits>True</IndentSubsplits>
        <HideSubsplits>False</HideSubsplits>
        <ShowSubsplits>False</ShowSubsplits>
        <CurrentSectionOnly>False</CurrentSectionOnly>
        <OverrideSubsplitColor>False</OverrideSubsplitColor>
        <SubsplitGradient>Plain</SubsplitGradient>
        <ShowHeader>True</ShowHeader>
        <IndentSectionSplit>True</IndentSectionSplit>
        <ShowIconSectionSplit>True</ShowIconSectionSplit>
        <ShowSectionIcon>True</ShowSectionIcon>
        <HeaderGradient>Vertical</HeaderGradient>
        <OverrideHeaderColor>False</OverrideHeaderColor>
        <HeaderText>True</HeaderText>
        <HeaderTimes>True</HeaderTimes>
        <HeaderAccuracy>Tenths</HeaderAccuracy>
        <SectionTimer>True</SectionTimer>
        <SectionTimerGradient>True</SectionTimerGradient>
        <SectionTimerAccuracy>Tenths</SectionTimerAccuracy>
        <SubsplitTopColor>8D000000</SubsplitTopColor>
        <SubsplitBottomColor>00FFFFFF</SubsplitBottomColor>
        <HeaderTopColor>2BFFFFFF</HeaderTopColor>
        <HeaderBottomColor>D8000000</HeaderBottomColor>
        <HeaderTextColor>FFFFFFFF</HeaderTextColor>
        <HeaderTimesColor>FFFFFFFF</HeaderTimesColor>
        <SectionTimerColor>FF777777</SectionTimerColor>
        <ShowColumnLabels>False</ShowColumnLabels>
        <LabelsColor>FFFFFFFF</LabelsColor>
        <Columns>
          <Settings>
            <Version>1.5</Version>
            <Name>+/-</Name>
            <Type>Delta</Type>
            <Comparison>Current Comparison</Comparison>
            <TimingMethod>Current Timing Method</TimingMethod>
          </Settings>
          <Settings>
            <Version>1.5</Version>
            <Name>Time</Name>
            <Type>SplitTime</Type>
            <Comparison>Current Comparison</Comparison>
            <TimingMethod>Current Timing Method</TimingMethod>
          </Settings>
        </Columns>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Timer.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <TimerHeight>69</TimerHeight>
        <TimerWidth>225</TimerWidth>
        <TimerFormat>1.23</TimerFormat>
        <OverrideSplitColors>True</OverrideSplitColors>
        <ShowGradient>True</ShowGradient>
        <TimerColor>FF632AAE</TimerColor>
        <BackgroundColor>00494243</BackgroundColor>
        <BackgroundColor2>FF222222</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <CenterTimer>False</CenterTimer>
        <TimingMethod>Current Timing Method</TimingMethod>
        <DecimalsSize>35</DecimalsSize>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.RunPrediction.dll</Path>
      <Settings>
        <Version>1.4</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <TimeColor>FFFFFFFF</TimeColor>
        <OverrideTimeColor>False</OverrideTimeColor>
        <Accuracy>Seconds</Accuracy>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Comparison>Current Comparison</Comparison>
        <Display2Rows>False</Display2Rows>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.SumOfBest.dll</Path>
      <Settings>
        <Version>1.4</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <TimeColor>FFFFFFFF</TimeColor>
        <OverrideTimeColor>False</OverrideTimeColor>
        <Accuracy>Seconds</Accuracy>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Display2Rows>False</Display2Rows>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.PreviousSegment.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BackgroundColor>00494243</BackgroundColor>
        <BackgroundColor2>FF494243</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <DeltaAccuracy>Tenths</DeltaAccuracy>
        <DropDecimals>True</DropDecimals>
        <Comparison>Current Comparison</Comparison>
        <Display2Rows>False</Display2Rows>
        <ShowPossibleTimeSave>False</ShowPossibleTimeSave>
        <TimeSaveAccuracy>Tenths</TimeSaveAccuracy>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.WorldRecord.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <TimeColor>FFFFFFFF</TimeColor>
        <OverrideTimeColor>False</OverrideTimeColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Display2Rows>False</Display2Rows>
        <CenteredText>True</CenteredText>
        <FilterRegion>False</FilterRegion>
        <FilterPlatform>False</FilterPlatform>
        <FilterVariables>False</FilterVariables>
        <FilterSubcategories>True</FilterSubcategories>
      </Settings>
    </Component>
  </Components>
</Layout>